# Use the official .NET image as a base for the final stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the csproj and restore as distinct layers
COPY ["ViFunction.KubeOps.csproj", "."]
RUN dotnet restore "ViFunction.KubeOps.csproj"

# Copy the rest of the application code
COPY . .
RUN dotnet build "ViFunction.KubeOps.csproj" -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish "ViFunction.KubeOps.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Final stage using a lightweight ASP.NET Core runtime image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ViFunction.KubeOps.dll"]