name: Deploy to GKE

on:
    push:
      branches:
        - refactor

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: sunlit-hook-450703-s2
  GCP_PROJECT_NUMBER: 843717978288
  GCP_WIF_POOL: github-actions-vi-function-test
  GCP_WIF_PROVIDER: github-actions-vi-functions-test
  GKE_CLUSTER: vifunction
  GKE_ZONE: us-central1
  REGISTRY: asia-southeast1-docker.pkg.dev

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:

      - name: Authenticate to Google Cloud via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          token_format: access_token
          workload_identity_provider: projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.GCP_WIF_POOL }}/providers/${{ env.GCP_WIF_PROVIDER }}
          service_account: github-actions@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Test Helm access using shell script
        run: |
            chmod +x ./src/deployments/install_app.sh
            ./src/deployments/install_app.sh
      
        
